name: Environments

on:
  workflow_dispatch

jobs:
  Dev:
    runs-on: ubuntu-latest
    environment: Development
    
    steps:
      - name: Deploy
        run: echo "Deployed on Dev environment"
      
  Stage:
    runs-on: ubuntu-latest
    environment: Staging
    needs: Dev
    steps:
      - name: Deploy
        run: echo "Deployed on Staging environment"
  
  Prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: Stage
    steps:
      - name: Deploy
        run: echo "Deployed on Production environment"
